### ISSUE TITLE
how do we send a notification to a group of users ???? 

### ISSUE THREAD

**Issue by ahmed-bhs** [groupfivesoftware/NotificationBundle#1]

**Comment by joshlopes** [comment]
@famas23 Why don't you loop the users of your group and send to each one a notification ?

**Comment by laurentiustroia** [comment]
Hi, if you want use it like a group notification, in Notification class use a user common field, like group:

### 1. User Entity

```php
 /**
    * @var string
    *
    * @ORM\Column(name="group", type="string")
    */
    private $group;
// generate setter/getter
```

### 2. Change jsonSerialize from Notification Entity
```php
public function jsonSerialize()
  {
      return [
          'type' => $this->getType(),
          'description' => $this->getDescription(),
          'checked' => $this->getChecked(),
          'checkedAt' => $this->getCheckedAt(),
          'createdAt' => $this->getCreateAt(),
          'url' => $this->url,
          'id' => $this->id,
          'userId' => $this->user->getGroup() //This helps the server identify if a specific users is connected and only send notifications to that user. You can use another field for common notifications, for example group notifications.
      ];
  }
```

**Comment by joshlopes** [comment]
@laurentiustroia what a hack 🙈

**Comment by laurentiustroia** [comment]
If you want change the Handler, is your option, but will be slow if you have many connection and you iterate it. `userId` is used to group the users, if you pass there a unique ID in Handler you will have Key => User, but if you not passed a unique ID the Handler will use key => array of users.
